### ISSUE TITLE
Windows 10 .exe does not run anything September 16 update

### ISSUE THREAD

**Issue by oreo8631** [KrisCris/Palworld-Pal-Editor#58] opened 2024-09-19 14:36 UTC
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [X] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

When downloading the .exe file and running it as administrator it does not load anything and has a black screen.

-I have tried using the gui fix and when trying to decompress it says data error.
- My windows security was temporarily turned off to make sure no files were removed.
- I have tried the python pip method. (i am not very code literate)

I appologize if i dont have all information needed this is my first time. Im more than happy to help and give more info if needed.

Thank you Kindly,
-Colin

### Expected Behaviour

Click the exe and it runs.

### Editor Version

0.9.0

### Game Version

0.3.7.58983

### Logs

![Pal world editor issue](https://github.com/user-attachments/assets/af216019-42a0-479d-83e9-5acaa733329c)

### Your Game Save

im on version 0.3.7.58983
Im not sure how to get you a game save file.

**Comment by dsteindo** [comment] 2024-09-20 11:05
It seems they changed the save file format

This is the powershell output for a save file from 0.3.7.58983

Command
```
python -m palworld_pal_editor
```

Output
```
2024-09-20 13:03:08 [INFO] Logs written to C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_pal_editor\logs
2024-09-20 13:03:08 [INFO] Config file written to C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_pal_editor\config.json
2024-09-20 13:03:08 [INFO] i18n: en, mode: gui, port: 58080, path: C:\Users\Comfy Shibe\AppData\Local\Pal\Saved\SaveGames\76561198351693593\1AB5E022419B663B446DA28C105FB01D, password: None, JWT_SECRET_KEY: X2Nvbm5sb3N0
2024-09-20 13:03:08 [INFO] Running Palworld-Pal-Editor version: sakura_pre5
2024-09-20 13:03:08 [INFO] Palworld Pal Editor vsakura_pre5, made by _connlost with ❤.
2024-09-20 13:03:08 [INFO] Waiting for backend response...

!Interactive Mode Enabled!
Thank you for using Palworld Pal Editor, made by _connlost with ❤.
Type pal_help() for Pal Editor help message
Type help(object) for help about object.
>>> 2024-09-20 13:03:08 [INFO] LISTENING ON 127.0.0.1:58080.
2024-09-20 13:03:08 [INFO] Backend ready, launching GUI...
2024-09-20 13:03:08 [INFO] If GUI doesn't work for you, check out this post: https://github.com/KrisCris/Palworld-Pal-Editor/issues/4
2024-09-20 13:03:13 [INFO] Opening C:\Users\Comfy Shibe\AppData\Local\Pal\Saved\SaveGames\76561198351693593\1AB5E022419B663B446DA28C105FB01D\Level.sav
2024-09-20 13:03:13 [INFO] Decompressing sav
2024-09-20 13:03:13 [INFO] Reading GVAS file
ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_pal_editor\api\save.py", line 35, in load
    if path and SaveManager().open(path):
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_pal_editor\core\save_manager.py", line 298, in open
    self.gvas_file = GvasFile.read(
                     ^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 515, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 542, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 477, in property
    value = self.prop_value(value_type, value_struct_type, value_path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 499, in prop_value
    return self.struct_value(struct_type_name, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 542, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 396, in property
    value = self.custom_properties[path][0](self, type_name, size, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\rawdata\character.py", line 13, in decode
    value["value"] = decode_bytes(reader, char_bytes)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\rawdata\character.py", line 22, in decode_bytes
    "object": reader.properties_until_end(),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 515, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 542, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Comfy Shibe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\palworld_save_tools\archive.py", line 493, in property
    raise Exception(f"Unknown type: {type_name} ({path})")
Exception: Unknown type: ByteProperty (.SaveParameter.Level)
```

**Comment by KrisCris** [comment] 2024-09-21 06:10
duplicate of #57

**Closed as completed** 2024-09-21 06:10 UTC
Labels: bug
