### ISSUE TITLE
Load data failed with sakura_pre5 version

### ISSUE THREAD

**Issue by lzptimeless** [KrisCris/Palworld-Pal-Editor#40] opened 2024-07-09 14:59 UTC
1. Launch with 'python -m palworld_pal_editor'
2. Select my pal data folder
3. Click 'Load Save'
4. An error dialog displayed: - loadSave - Error occured: undefined

This is the exception detail in console:
ERROR:palworld_pal_editor.webui:Exception on /api/save/load [POST]
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\flask_jwt_extended\view_decorators.py", line 170, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_pal_editor\api\save.py", line 35, in load
    if path and SaveManager().open(path):
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_pal_editor\core\save_manager.py", line 297, in open
    self.gvas_file = GvasFile.read(
                     ^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\gvas.py", line 131, in read
    gvas_file.properties = reader.properties_until_end()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\archive.py", line 399, in property
    value = self.struct(path)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\archive.py", line 510, in struct
    value = self.struct_value(struct_type, path)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\archive.py", line 537, in struct_value
    return self.properties_until_end(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\archive.py", line 386, in properties_until_end
    properties[name] = self.property(type_name, size, f"{path}.{name}")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Scoop\apps\python311\current\Lib\site-packages\palworld_save_tools\archive.py", line 488, in property
    raise Exception(f"Unknown type: {type_name} ({path})")
Exception: Unknown type: UInt32Property (.worldSaveData.WorldMetaSaveVersionBitMask)

**System:**
 - OS: Windows 11, 10.0.22621
 - Software Version: sakura_pre5

**Comment by KrisCris** [comment] 2024-07-09 19:12
Duplicate of #38

**Closed as completed** 2024-07-09 19:12 UTC

**Comment by KrisCris** [comment] 2024-07-10 01:01
If you are using the pypi package, I have revoked v0.9.0 as it was released by accident.
