### ISSUE TITLE
Help: WebUI and Remote Access

### ISSUE THREAD

**Issue by AverilLuo** [KrisCris/Palworld-Pal-Editor#9] opened 2024-04-01 05:18 UTC
![Screenshot](https://github.com/KrisCris/Palworld-Pal-Editor/assets/144874459/9b8bef88-53f6-4e68-bd30-1df2dffdb141)
and the log file is [here](https://github.com/KrisCris/Palworld-Pal-Editor/files/14819521/2024-04-01_12-01-51.log) if needed
[Ubuntu Server 22.04 LTS 64bit]

I'm using the pre build artifact for ubuntu from the release page, and i installed pywebview things by following [this guide](https://pywebview.flowrl.com/guide/installation.html) but nothing changed, i can't 100% sure my installation is correct and complete because to be honest (and pretty obvious) i'm just officially so suck at this, maybe all i really need is just a working installation step, but i did try everything i could, please help!!

Best regards

**Comment by KrisCris** [comment] 2024-04-01 05:30
Did the tool open a web page for you? if not, can you try manually open this webpage: 127.0.0.1:58080

Tbh I am not sure how to fix this, but, I am going to find a way to workaround this.

Duplicate of https://github.com/KrisCris/Palworld-Pal-Editor/issues/4

**Comment by AverilLuo** [comment] 2024-04-01 06:25
Thanks for such a quick reply,
It didn't open the web page for me, i ran it on the vps via my terminal, i tried using the browser on my PC to access  server_public_ip:58080, and the page returned "This page isn’t working, *ip_address* is currently unable to handle this request" which is http error 503

**Comment by KrisCris** [comment] 2024-04-01 06:26
I see.

In case you don't have a GUI, you can run the program with `--mode web` arg, this way it listens on 0.0.0.0 so you can remote access.

Also setting up a password to protect unauthorized access.

i.e. `./palworld_pal_editor --mode web --password your_password`

**Comment by AverilLuo** [comment] 2024-04-01 06:39
I really appreciate it, i've done that in config.json, it worked

**Comment by KrisCris** [comment] 2024-04-01 06:42
Glad to hear that!

Issue close as resolved

**Closed as completed by KrisCris** 2024-04-01 06:42 UTC
