### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by mignit** [KrisCris/Palworld-Pal-Editor#62] opened 2024-09-29 14:21 UTC
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have read the [README](https://github.com/KrisCris/Palworld-Pal-Editor?tab=readme-ov-file#palworld-pal-editor)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).
- [x] I have checked for both game and editor updates, and understand that issues on older versions may not be resolved.

### Bug Report Description

As shown in the picture.
![screen](https://github.com/user-attachments/assets/06ef389b-19d7-40e2-9da3-b85d584fb30c)

### Expected Behaviour

cant use.

### Editor Version

0.9.0

### Game Version

0.3.3

### Logs

2024-09-21_22-59-?.log

### Your Game Save

[0BF6F4C840A9946CE28D3AB1046EEFDC.zip](https://github.com/user-attachments/files/17179547/0BF6F4C840A9946CE28D3AB1046EEFDC.zip)

**Comment by KrisCris** [comment] 2024-09-29 23:44
duplicate of #57

**Closed as completed** 2024-09-29 23:44 UTC
Labels: bug
