### ISSUE TITLE
MIME Type Error

### ISSUE THREAD

**Issue by nrlearn** [KrisCris/Palworld-Pal-Editor#15] opened 2024-04-05 04:45 UTC
Thank you for the application.

When I uses Palworld-Pal-Editor on pypi with web mode, it  has an error "Failed to load module script..." in browser

**To Reproduce**
```
conda create -m testenv python==3.11
conda activate testenv
conda install pip
pip install palworld-pal-editor
python -m palworld_pal_editor --mode web
```

**Expected behavior**
it shows error in edge browser or chrome browser

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

**Screenshots**
![Snipaste_2024-04-05_12-32-50](https://github.com/KrisCris/Palworld-Pal-Editor/assets/29811500/76e09418-9189-4b66-bee1-b33478b259be).

**Desktop (please complete the following information):**
 - OS: win11
 - edge(123.0.2420.65,64-bit),chrome(123.0.6312.106 (Official Build) (64-bit))

**Comment by KrisCris** [comment] 2024-04-05 04:54
Which version are you using? I am unable to reproduce this issue.

![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860226/5b5c5bed-9997-4e7e-9a21-6c53988352ea)

Likely the same issue: https://github.com/KrisCris/Palworld-Pal-Editor/issues/8#issuecomment-2036407453

Is this your first time running this tool? If not, try :
- Unregister service workers (In the Application tab) if one is loaded (We used to have PWA support but I removed it due to some issues)
- ![image](https://github.com/KrisCris/Palworld-Pal-Editor/assets/38860226/0d18220a-4ca1-4da2-945d-c52961751286)
- Force refresh the page (Hold `Shift` then click the refresh button)

**Comment by nrlearn** [comment] 2024-04-05 05:16
> Which version are you using? I am unable to reproduce this issue.
> 
> ![image](https://private-user-images.githubusercontent.com/38860226/319861784-5b5c5bed-9997-4e7e-9a21-6c53988352ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTM4MDAsIm5iZiI6MTcxMjI5MzUwMCwicGF0aCI6Ii8zODg2MDIyNi8zMTk4NjE3ODQtNWI1YzViZWQtOTk5Ny00ZTdlLTlhMjEtNmM1Mzk4ODM1MmVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA1MDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMDJkYWU0YTgwZjM1ODdmODMzZTM2YTEwMTU1YjIzNTI1MzIwMWY0YmQ4YmM3MTkwZGUyNWZjMzhmZWIyM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OzdN4_so41UGMsvUFstxgFFFPr3dIqTI77cKj38i6a0)
> 
> Likely the same issue: [#8 (comment)](https://github.com/KrisCris/Palworld-Pal-Editor/issues/8#issuecomment-2036407453)
> 
> Is this your first time running this tool? If not, try :
> 
> * Unregister service workers (In the Application tab) if one is loaded (We used to have PWA support but I removed it due to some issues)
> * ![image](https://private-user-images.githubusercontent.com/38860226/319862701-0d18220a-4ca1-4da2-945d-c52961751286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyOTM4MDAsIm5iZiI6MTcxMjI5MzUwMCwicGF0aCI6Ii8zODg2MDIyNi8zMTk4NjI3MDEtMGQxODIyMGEtNGNhMS00ZGEyLTk0NWQtYzUyOTYxNzUxMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDA1MDUwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNjJiYzAxOWY4ZjVhMTRhN2IxZTQ4NzM5YjM5ZmI0N2Q3NzUzYzY2ZDFhMDY3ZDc0YWYyMzRhMGJiNTUyNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uYCm0XkhEMlyKhrqAkViek-e-TcsxJ_cPZBnhNyhpHc)
> * Force refresh the page (Hold `Shift` then click the refresh button)

The vision is 0.4.1.post2,this is my first time to run this tool. I tried the steps,but it didn't work.
![chrome1](https://github.com/KrisCris/Palworld-Pal-Editor/assets/29811500/d4c62086-77f5-4666-93e1-cf3250ee6801)

I has searched this error message, it seems to be a windows platform specific problem, wish it helps.
https://github.com/jupyterlite/jupyterlite/issues/569

**Comment by KrisCris** [comment] 2024-04-05 05:18
> I has searched this error message, it seems to be a windows platform specific problem, wish it helps.

I had just realized this issue, and have pushed a fix.

**Comment by KrisCris** [comment] 2024-04-05 05:18
Can you test if `pip install palworld-pal-editor==0.4.2` fix the issue

**Comment by nrlearn** [comment] 2024-04-05 05:20
> Can you test if `pip install palworld-pal-editor==0.4.2` fix the issue

no problem,wait for a while

**Comment by nrlearn** [comment] 2024-04-05 05:23
> Can you test if `pip install palworld-pal-editor==0.4.2` fix the issue

It fixed! thank you!

**Comment by KrisCris** [comment] 2024-04-05 05:24
Thank you for reporting this issue!

**Closed as completed by KrisCris** 2024-04-05 05:24 UTC
